/**
 * Curated emoji set for the chat composer.
 *
 * Hand-rolled rather than a package: emoji-mart and friends ship a 1–2 MB JSON
 * index plus sprite sheets, which is absurd next to a support chat that needs a
 * few hundred glyphs. Every entry carries search keywords so typing "money" or
 * "chai" finds the right one — the only thing the big libraries really buy you.
 */

export interface EmojiEntry {
  /** The glyph itself. */
  char: string;
  /** Space-separated search terms, lowercase. */
  keywords: string;
}

export interface EmojiGroup {
  id: string;
  label: string;
  /** Tab icon — an emoji, so the tab bar needs no icon font. */
  icon: string;
  emojis: EmojiEntry[];
}

const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords });

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😊',
    emojis: [
      e('😀', 'grin smile happy'),
      e('😃', 'smile happy joy'),
      e('😄', 'smile happy laugh'),
      e('😁', 'grin beam happy'),
      e('😆', 'laugh satisfied'),
      e('😅', 'sweat laugh relief'),
      e('🤣', 'rofl laughing rolling'),
      e('😂', 'joy tears laugh'),
      e('🙂', 'slight smile'),
      e('🙃', 'upside down silly'),
      e('😉', 'wink'),
      e('😊', 'blush smile happy'),
      e('😇', 'innocent halo angel'),
      e('🥰', 'love hearts adore'),
      e('😍', 'heart eyes love'),
      e('😘', 'kiss blow'),
      e('😋', 'yum tasty delicious'),
      e('😛', 'tongue playful'),
      e('🤗', 'hug hugging'),
      e('🤔', 'thinking hmm consider'),
      e('🤨', 'raised eyebrow skeptic'),
      e('😐', 'neutral meh'),
      e('😑', 'expressionless blank'),
      e('🙄', 'eye roll annoyed'),
      e('😬', 'grimace awkward'),
      e('😴', 'sleep tired zzz'),
      e('😌', 'relieved calm'),
      e('😔', 'sad pensive down'),
      e('😟', 'worried concerned'),
      e('😕', 'confused unsure'),
      e('🙁', 'frown slight sad'),
      e('😖', 'confounded frustrated'),
      e('😣', 'persevere struggle'),
      e('😞', 'disappointed sad'),
      e('😩', 'weary tired exhausted'),
      e('😤', 'triumph steam angry'),
      e('😠', 'angry mad'),
      e('😡', 'rage furious angry'),
      e('🥺', 'pleading please beg'),
      e('😢', 'cry sad tear'),
      e('😭', 'sob crying loud'),
      e('😰', 'anxious sweat nervous'),
      e('😱', 'scream shock fear'),
      e('🤯', 'mind blown shocked'),
      e('😳', 'flushed embarrassed'),
      e('🥳', 'party celebrate hooray'),
      e('😎', 'cool sunglasses'),
      e('🤓', 'nerd glasses'),
      e('🫡', 'salute yes sir'),
      e('🤝', 'handshake deal agree'),
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures',
    icon: '👍',
    emojis: [
      e('👍', 'thumbs up yes good approve ok'),
      e('👎', 'thumbs down no bad reject'),
      e('👌', 'ok perfect fine'),
      e('🤌', 'pinched fingers'),
      e('✌️', 'peace victory'),
      e('🤞', 'fingers crossed hope luck'),
      e('🫰', 'money fingers snap'),
      e('👏', 'clap applause well done'),
      e('🙌', 'raise hands celebrate praise'),
      e('🙏', 'pray thanks please namaste'),
      e('💪', 'strong muscle power'),
      e('🤙', 'call me shaka'),
      e('👋', 'wave hello hi bye'),
      e('🖐️', 'hand stop five'),
      e('☝️', 'point up one'),
      e('👉', 'point right'),
      e('👈', 'point left'),
      e('👇', 'point down'),
      e('✍️', 'writing sign note'),
      e('🫵', 'point you'),
    ],
  },
  {
    id: 'people',
    label: 'People',
    icon: '🧑',
    emojis: [
      e('🧑', 'person adult'),
      e('👨', 'man'),
      e('👩', 'woman'),
      e('🧔', 'beard man'),
      e('👴', 'old man elder'),
      e('👵', 'old woman elder'),
      e('👶', 'baby child'),
      e('🧑‍🍳', 'cook chef'),
      e('🧑‍💼', 'office worker business'),
      e('🧑‍🔧', 'mechanic engineer repair'),
      e('🧑‍💻', 'developer laptop tech'),
      e('👮', 'police officer'),
      e('🕵️', 'detective investigate'),
      e('🚴', 'cyclist bike delivery'),
      e('🏃', 'run running fast'),
      e('🧍', 'standing waiting'),
      e('👥', 'people group users'),
      e('👤', 'person silhouette user'),
      e('🤦', 'facepalm'),
      e('🤷', 'shrug dunno'),
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '☕',
    emojis: [
      e('☕', 'tea chai coffee hot drink cup'),
      e('🫖', 'teapot chai tea kettle'),
      e('🍵', 'green tea matcha cup'),
      e('🧉', 'mate drink'),
      e('🥤', 'cold drink cup straw'),
      e('🧊', 'ice cold cube'),
      e('🥛', 'milk glass doodh'),
      e('🍶', 'sake bottle'),
      e('🍪', 'biscuit cookie khari'),
      e('🥠', 'fortune cookie'),
      e('🍞', 'bread bun pav'),
      e('🥐', 'croissant bakery'),
      e('🧈', 'butter'),
      e('🥟', 'dumpling momo samosa'),
      e('🍲', 'curry bowl food'),
      e('🍛', 'rice curry meal'),
      e('🌶️', 'chilli spicy masala'),
      e('🫚', 'ginger adrak root'),
      e('🥜', 'peanut nut'),
      e('🍬', 'candy sweet elaichi'),
      e('🎂', 'cake birthday'),
      e('🍽️', 'plate cutlery meal'),
    ],
  },
  {
    id: 'business',
    label: 'Work',
    icon: '💰',
    emojis: [
      e('💰', 'money bag cash payment'),
      e('💵', 'cash note dollar'),
      e('💸', 'money flying spend payment'),
      e('💳', 'card payment credit'),
      e('🧾', 'receipt invoice bill'),
      e('📊', 'chart bar analytics report'),
      e('📈', 'chart up growth increase'),
      e('📉', 'chart down decline loss'),
      e('🗓️', 'calendar date schedule'),
      e('📅', 'calendar date'),
      e('⏳', 'hourglass waiting pending'),
      e('⏰', 'alarm clock reminder time'),
      e('📌', 'pin important'),
      e('📎', 'paperclip attachment file'),
      e('📁', 'folder files'),
      e('📄', 'document page file'),
      e('✏️', 'pencil edit write'),
      e('🔑', 'key password access'),
      e('🔒', 'lock blocked secure'),
      e('🔓', 'unlock open access'),
      e('🛒', 'cart order shopping'),
      e('🏪', 'shop store stall vendor'),
      e('🏠', 'home house address'),
      e('📍', 'location pin area'),
      e('🚚', 'delivery truck route'),
      e('📞', 'phone call'),
      e('📱', 'mobile phone device'),
      e('💻', 'laptop computer'),
      e('📧', 'email mail message'),
      e('🔔', 'bell notification alert'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '✅',
    emojis: [
      e('✅', 'check done yes complete tick'),
      e('☑️', 'checkbox done'),
      e('❌', 'cross no wrong error'),
      e('⛔', 'no entry blocked stop'),
      e('⚠️', 'warning caution alert'),
      e('❗', 'exclamation important'),
      e('❓', 'question help'),
      e('💡', 'idea bulb tip'),
      e('🔥', 'fire hot trending'),
      e('⭐', 'star favourite rating'),
      e('🌟', 'glowing star special'),
      e('🎉', 'party celebrate tada'),
      e('🎊', 'confetti celebrate'),
      e('🚀', 'rocket launch fast release'),
      e('🏆', 'trophy win leader best'),
      e('🥇', 'gold medal first'),
      e('❤️', 'heart love red'),
      e('💚', 'green heart'),
      e('👀', 'eyes look watch'),
      e('🙈', 'see no evil monkey'),
      e('💯', 'hundred perfect score'),
      e('🆗', 'ok button'),
      e('🆕', 'new'),
      e('🔄', 'refresh sync repeat renew'),
      e('➕', 'plus add'),
      e('➖', 'minus remove'),
      e('🔴', 'red circle live'),
      e('🟢', 'green circle active online'),
      e('🟡', 'yellow circle pending'),
      e('⚫', 'black circle offline'),
    ],
  },
];

/** Flat index used by the search box. */
export const ALL_EMOJI: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emojis);
